# 🚨 Attention, le code présent dans ce fichier contient volontairement de nombreuses imperfections :
# 🚨 erreurs de conception, mauvaises pratiques de développement logiciel, failles de sécurité et de performance.
# 🚨 Ce code servira de support à un exercice de refactoring.
version: "3.9"

networks:
  rps:
    driver: bridge

services:
  api:
    image: node:lts-alpine
    container_name: rps-api
    env_file:
      - .env
    working_dir: /usr/src/app
    command: sh -c "npm i && npm start"
    ports:
      - 3000:3000
    volumes:
      - ./api:/usr/src/app
    links:
      - db
    networks:
      - rps
  db:
    image: mariadb
    container_name: rps-db
    env_file:
      - .env
    networks:
      - rps
  adminer:
    image: adminer
    container_name: rps-adminer
    environment:
      - ADMINER_DEFAULT_SERVER=rps-db
    ports:
      - 8181:8080
    networks:
      - rps
# 🚨 Attention, le code présent dans ce fichier contient volontairement de nombreuses imperfections :
# 🚨 erreurs de conception, mauvaises pratiques de développement logiciel, failles de sécurité et de performance.
# 🚨 Ce code servira de support à un exercice de refactoring.
